# Generated by Django 4.0.5 on 2022-06-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('ethnie', models.CharField(max_length=100)),
                ('numero_cni', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('age', models.PositiveBigIntegerField()),
                ('idf', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentRecenseur',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('ethnie', models.CharField(max_length=100)),
                ('numero_cni', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('age', models.PositiveBigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonateurAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DonateurId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('mdp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('sous_prefecture', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('ethnie', models.CharField(max_length=100)),
                ('numero_cni', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('age', models.PositiveBigIntegerField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DonateurEta',
            fields=[
                ('donateurid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crud.donateurid')),
                ('Ministere', models.CharField(max_length=100)),
            ],
            bases=('crud.donateurid',),
        ),
        migrations.CreateModel(
            name='Recenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religion', models.CharField(max_length=100)),
                ('survie_mere', models.CharField(max_length=100)),
                ('survie_pere', models.CharField(max_length=100)),
                ('alphabetisation', models.CharField(max_length=100)),
                ('niveau_instruction', models.CharField(max_length=100)),
                ('statut_occup', models.CharField(max_length=100)),
                ('occupation_actu', models.CharField(max_length=100)),
                ('branche_activite', models.CharField(max_length=100)),
                ('situation_matr', models.CharField(max_length=100)),
                ('type_mariage', models.CharField(max_length=100)),
                ('nombre_enfant', models.CharField(max_length=100)),
                ('nombre_enfant_v', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.parents')),
            ],
            options={
                'ordering': ['parent'],
            },
        ),
        migrations.CreateModel(
            name='Migrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deplace', models.BooleanField()),
                ('annee_deplace', models.DateField()),
                ('lieu_residence_a', models.CharField(max_length=100)),
                ('intention_ret', models.BooleanField()),
                ('parentm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.parents')),
            ],
            options={
                'ordering': ['parentm'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen_deplacement', models.CharField(max_length=100)),
                ('equipement_electr', models.CharField(max_length=100)),
                ('equipement_audio', models.CharField(max_length=100)),
                ('statut_occupation', models.CharField(max_length=100)),
                ('parente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.parents')),
            ],
            options={
                'ordering': ['parente'],
            },
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('ethnie', models.CharField(max_length=100)),
                ('numero_cni', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('age', models.PositiveBigIntegerField()),
                ('ecolier', models.CharField(blank=True, default='oui', max_length=100)),
                ('id1', models.BigAutoField(primary_key=True, serialize=False)),
                ('parentf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.parents')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectuerDonId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible', models.CharField(blank=True, max_length=100)),
                ('categorie', models.FloatField(default=0)),
                ('nature', models.CharField(blank=True, max_length=100)),
                ('lieu_reception', models.CharField(blank=True, max_length=100)),
                ('photo', models.CharField(blank=True, max_length=100)),
                ('Etat', models.CharField(blank=True, max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('montant', models.FloatField(default=0)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.donateurano')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectuerDonAno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible', models.CharField(blank=True, max_length=100)),
                ('categorie', models.FloatField(default=0)),
                ('nature', models.CharField(blank=True, max_length=100)),
                ('lieu_reception', models.CharField(blank=True, max_length=100)),
                ('photo', models.CharField(blank=True, max_length=100)),
                ('Etat', models.CharField(blank=True, max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('montant', models.FloatField(default=0)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.donateurid')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexesd', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('age_deces', models.PositiveBigIntegerField()),
                ('nom_decede', models.CharField(max_length=100)),
                ('prenom_decede', models.CharField(max_length=100)),
                ('annee_deces', models.DateField()),
                ('parentd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.parents')),
            ],
            options={
                'ordering': ['parentd'],
            },
        ),
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_piece', models.CharField(max_length=100)),
                ('nature_mur', models.CharField(max_length=100)),
                ('nature_toit', models.CharField(max_length=100)),
                ('nature_sol', models.CharField(max_length=100)),
                ('alimentation_eau', models.CharField(max_length=100)),
                ('eclairage', models.CharField(max_length=100)),
                ('cuisson', models.CharField(max_length=100)),
                ('evacuation_ordure', models.CharField(max_length=100)),
                ('evacuation_eau', models.CharField(max_length=100)),
                ('loyer', models.CharField(max_length=100)),
                ('parentc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.parents')),
            ],
            options={
                'ordering': ['parentc'],
            },
        ),
        migrations.CreateModel(
            name='Affecter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexes', models.CharField(choices=[('M', 'Maxculin'), ('F', 'Feminin')], max_length=1)),
                ('ethnie', models.CharField(max_length=100)),
                ('numero_cni', models.CharField(max_length=100)),
                ('annee_naissance', models.DateField()),
                ('age', models.PositiveBigIntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('agentr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.agentrecenseur')),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.localite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectuerDonEta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cible', models.CharField(blank=True, max_length=100)),
                ('categorie', models.FloatField(default=0)),
                ('nature', models.CharField(blank=True, max_length=100)),
                ('lieu_reception', models.CharField(blank=True, max_length=100)),
                ('photo', models.CharField(blank=True, max_length=100)),
                ('Etat', models.CharField(blank=True, max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('montant', models.FloatField(default=0)),
                ('provider', models.CharField(blank=True, max_length=100)),
                ('donateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.donateureta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
