# Generated by Django 4.0.5 on 2022-06-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affecter',
            name='age',
        ),
        migrations.RemoveField(
            model_name='affecter',
            name='annee_naissance',
        ),
        migrations.RemoveField(
            model_name='affecter',
            name='ethnie',
        ),
        migrations.RemoveField(
            model_name='affecter',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='affecter',
            name='numero_cni',
        ),
        migrations.RemoveField(
            model_name='affecter',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='affecter',
            name='sexes',
        ),
    ]
