# Generated by Django 4.0.5 on 2022-06-20 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_affecter_age_remove_affecter_annee_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effectuerdonano',
            name='categorie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonano',
            name='donateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.donateurano'),
        ),
        migrations.AlterField(
            model_name='effectuerdonano',
            name='montant',
            field=models.FloatField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdoneta',
            name='categorie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdoneta',
            name='montant',
            field=models.FloatField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonid',
            name='categorie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='effectuerdonid',
            name='donateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.donateurid'),
        ),
        migrations.AlterField(
            model_name='effectuerdonid',
            name='montant',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
