# Generated by Django 4.0.5 on 2022-07-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_effectuerdonano_categorie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recenser',
            old_name='occupation_actu',
            new_name='occupation_actuelle',
        ),
        migrations.RenameField(
            model_name='recenser',
            old_name='situation_matr',
            new_name='situation_matrimoniale',
        ),
        migrations.RenameField(
            model_name='recenser',
            old_name='statut_occup',
            new_name='statut_occupation',
        ),
        migrations.AddField(
            model_name='admins',
            name='nationalite',
            field=models.CharField(default='ivoirienne', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentrecenseur',
            name='nationalite',
            field=models.CharField(default='ivoirienne', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enfant',
            name='nationalite',
            field=models.CharField(default='ivoirienne', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parents',
            name='nationalite',
            field=models.CharField(default='ivoirienne', max_length=100),
            preserve_default=False,
        ),
    ]
